# (PART\*) Modèles additifs généralisés en `R` {-}

# Objectifs d'apprentissage

L'objectif de l'atelier d'aujourd'hui sera d'examiner
ce que nous entendons par un modèle non-linéaire et comment les GAMs
(modèles additifs généralisés) nous permettent de modéliser les
relations non-linéaires. Nous examinerons également comment tracer et
interpréter ces relations non-linéaires, comment ajouter des
interactions, comment prendre en compte la non-indépendance des données
(*e.g.* erreurs autocorrélées) et comment inclure des effets aléatoires
en se basant sur les ateliers précédents. Enfin, nous allons brièvement
aborder la mécanique derrière le fonctionnement des GAMs.

Nous vous recommandons d'avoir une certaine expérience de R, en particulier de la consultation de données et d'objets dans des scripts R, et une connaissance de base de la régression linéaire avant de suivre cet atelier.

Plus spécifiquement, cet atelier portera sur comment:

1.  Utiliser la librairie *mgcv* pour modéliser les relations non
    linéaires
2.  Évaluer la sortie d'un GAM afin de mieux comprendre nos données
3.  Utiliser des tests pour déterminer si nos relations correspondent à
    des modèles non linéaires ou linéaires
4.  Ajouter des interactions non linéaires entre les variables
    explicatives
5.  Comprendre l'idée d'une fonction de base (*basis function*) et la
    raison pour laquelle ça rend les GAMs si puissants !
6.  Comment modéliser la dépendance dans les données (autocorrélation,
    structure hiérarchique) en utilisant les GAMMs


# Préparez-vous pour cet atelier

Tout le matériel de l'atelier se trouve sur [r.qcbs.ca/fr/workshops/r-workshop-08/](https://r.qcbs.ca/fr/workshops/r-workshop-08/). Cela inclut un [script R](https://r.qcbs.ca/workshop08/book-fr/workshop08-script-fr.R) qui rassemble tous les morceaux de code présentés dans ce livre.

Pour cet atelier, nous travaillerons avec les jeux de données suivants :

* [ISIT.csv](https://r.qcbs.ca/workshop08/pres-en/data/ISIT.csv) 
* [other_dist.csv](https://r.qcbs.ca/workshop08/pres-en/data/other_dist.csv) 

Vous devriez également vous assurer que vous avez téléchargé, installé et chargé les paquets R suivants:

* [ggplot2](https://cran.r-project.org/package=ggplot2)
* [itsadug](https://cran.r-project.org/package=itsadug)
* [mgcv](https://cran.r-project.org/package=mgcv)

```{r, echo = TRUE, eval = TRUE, message= FALSE, warning = FALSE, results = 'hide'}
install.packages("ggplot2")
install.packages("mgcv")
install.packages("itsadug")

library(ggplot2)
library(mgcv)
library(itsadug)
```
